---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2021-10-18"
description: GDP components for countries # the title that will show up once someone gets to this page
dge: spices.jpg # save picture in \static\img\blogs. Acceptable formats= jpg, jpeg, or png . Your iPhone pics wont work

keywords: ""
slug: gdp_countries # slug is the shorthand URL address... no spaces plz
title: GDP Components Analysis for Different Countries
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries, echo=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(GGally)
library(readxl)
library(here)
library(skimr)
library(janitor)
library(broom)
library(tidyquant)
library(infer)
library(openintro)
```

```{r read_GDP_data}

UN_GDP_data  <-  read_excel(here::here("data", "Download-GDPconstant-USD-countries.xlsx"), # Excel filename
                sheet="Download-GDPconstant-USD-countr", # Sheet name
                skip=2) # Number of rows to skip


head(UN_GDP_data)

```

```{r reshape_GDP_data}

ncol(UN_GDP_data) 

tidy_GDP_data  <- UN_GDP_data %>%  
  pivot_longer(cols = 4:51, #columns 4 to 51
               names_to = "Year",
               values_to = "Country_GDP") %>% 
  mutate(Country_GDP = Country_GDP/1e9)

head(tidy_GDP_data)
```
```{r, fig.width = 8, fig.height = 8}
country_list <- c("United States","India", "Germany") #Compare GDP components for these 3 countries


unique(tidy_GDP_data[c("IndicatorName")])
```

```{r, fig.width = 10, fig.height = 6}
raw_GDP_component_list <- c("Gross capital formation", "Exports of goods and services", "General government final consumption expenditure", "Household consumption expenditure (including Non-profit institutions serving households)", "Imports of goods and services", "Gross Domestic Product (GDP)")

GDP_component_list <- c("Gross capital formation", "Exports", "Government expenditure", "Household expenditure","Imports","GDP")

three_countries_data <- tidy_GDP_data %>% 
  filter(Country %in% country_list) %>% 
  mutate(IndicatorName = factor(IndicatorName,
                                levels = raw_GDP_component_list,
                                labels = GDP_component_list)) %>% 
    filter(IndicatorName %in% GDP_component_list) 

three_countries_data_no_GDP <- three_countries_data %>% 
  filter(IndicatorName != "GDP")

#head(plot_three_countries)

plot_three_countries <- ggplot(three_countries_data_no_GDP, aes(x = Year, 
                                 y = Country_GDP, 
                                 group = IndicatorName, 
                                 colour = IndicatorName))+
  scale_x_discrete(breaks = seq(1970, 2020, by = 10)) +
  geom_line(size = 1) +
  facet_wrap(vars(Country), scales = "free_x") +
  theme_bw()+
  labs (
    title = "GDP components over time",
    subtitle = "In constant 2010 USD",
    x = "",
    y = "Billion US$" ) + 
  guides(color=guide_legend(title="Components of GDP")) +
  NULL

plot_three_countries


```
